### ISSUE TITLE
EndlessRecyclerView crashed when using recycler view library 23.2.0

### ISSUE THREAD

**Issue by jakubkrolewski** [yasevich/endless-recycler-view#9]
java.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling
  at android.support.v7.widget.RecyclerView.assertNotInLayoutOrScroll(RecyclerView.java:2161)
  at android.support.v7.widget.RecyclerView$RecyclerViewDataObserver.onChanged(RecyclerView.java:4249)
  at android.support.v7.widget.RecyclerView$AdapterDataObservable.notifyChanged(RecyclerView.java:9924)
  at android.support.v7.widget.RecyclerView$Adapter.notifyDataSetChanged(RecyclerView.java:5741)
  at com.allegrogroup.android.external.EndlessRecyclerView.setRefreshing(EndlessRecyclerView.java:210)
  at com.allegrogroup.android.external.EndlessRecyclerView$EndlessScrollListener.onScrolled(EndlessRecyclerView.java:250)
  at com.allegrogroup.android.external.EndlessRecyclerView$OnScrollListenerImpl.onScrolled(EndlessRecyclerView.java:218)
  at android.support.v7.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:3944)
  at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3102)
  at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2914)
  at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3277)

**Comment by yasevich** [comment]
Thanks for reporting this. Working on it.
